### ISSUE TITLE
[Bug] Team Leaders switch to their binocs too much when in danger mode

### ISSUE THREAD

**Issue by Leopard20** [robalo/mods#10]
They're always using their binocs instead of their primary weapon!

**Comment by robalo** [comment]
I noticed excessive binocs usage, but does it happen only with asr ai enabled ? Because I can't find any explanation if that is.

**Comment by Leopard20** [comment]
I realized that it's actually because of the recent changes to the AI by Bohemia. So it's not your fault!
My apologies. I mentioned it on BI forum but I forgot to close this.
