### ISSUE TITLE
[Linux] Missing Addon Dependency

### ISSUE THREAD

**Issue by SoraBytes** [robalo/mods#14]
Is the dependency on "A3_Data_F_Destroyer_Loadorder" important? ASR_AI3 has it as an addon dependency. My server & game both complain.. and the server will not load anything and it spams in the chat about missing a config.

**Comment by robalo** [comment]
It is basically saying you need the latest version of the game. Update to 1.84.

**Comment by SoraBytes** [comment]
I tagged [Linux] because I am using the Linux/mac port. "Update to 1.84" is out of the question until the company BI is paying to port the game releases it.

I simply wanted to know if the addon dependency was import enough to be required, or if it could at least be removed to support Linux/mac (1.82) since we do not yet have the Encore update.
