### ISSUE TITLE
AAF AI at checkpoint in mission Drawdown 2035 open fire

### ISSUE THREAD

**Issue by Leopard20** [robalo/mods#3]
In the mission Drawdown 2035 (first mission of the main campaign) when you drive the truck to the checkpoint (where you're supposed to stop) the AAF soldier behind the mounted MG starts firing at you. Is there anything you can do to fix it?

**Comment by robalo** [comment]
Try it with Incognito disabled in settings.

**Comment by Leopard20** [comment]
It's disabled already. Have you tried the mission yourself?
P.S: What is incognito mode? Is it for stealth or something?
