### ISSUE TITLE
Unable to load on a MP server

### ISSUE THREAD

**Issue by JMaverick8th** [robalo/mods#6]
Hello

Having some issues getting this to work on our dedicated server, i keep getting
"Script\user.config\asr_ai3\asr_ai3_config.sqf not found

However i did place it in the config folder, trying to run http://steamcommunity.com/sharedfiles/filedetails/?id=1118331280&searchtext=Hearts+and+Minds+Lythium this scenario on the server

**Comment by JMaverick8th** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=1118331280&searchtext=Hearts+and+Minds+Lythium

**Comment by robalo** [comment]
Put the asr_ai3 dir containing asr_ai3_config.sqf file inside your main arma dir under userconfig like this:
<Arma 3 dir>\userconfig\asr_ai3\asr_ai3_config.sqf

**Comment by JMaverick8th** [comment]
Ive tried that, still says the file is missing, do I need to do the same thing on my PC? I just subscribed to it on steam.

**Comment by JMaverick8th** [comment]
Fixed it, thanks for the help :)
